import 'dotenv/config';
import postgres from 'postgres';
import { drizzle } from 'drizzle-orm/postgres-js';
import { pgTable, text, integer } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';

const cxItemsTable = pgTable('cx_items', {
  id: text('id').primaryKey(),
  module: text('module').notNull().default(''),
  type: text('type').notNull().default('mejora'),
  priority: text('priority').notNull().default(''),
  description: text('description').notNull().default(''),
  status: text('status').notNull().default('sin-evaluar'),
  position: integer('position').notNull().default(0),
});

const client = postgres(process.env.DATABASE_URL!);
const db = drizzle(client);

const ITEMS = [
  { id: 'CX-375', module: 'Reporte', priority: 'baja', description: `Consulta de Relatório — "Ordem dos arquivos" não é uma tradução apropriada para a etapa de ordem das colunas; a tradução adequada deve ser revisada; Sugere-se "Ordenação de Colunas".` },
  { id: 'CX-379', module: 'Reporte', priority: 'baja', description: `Tradução de Filtro de Status — Ao filtrar, o campo de Status exibe os valores Habilitar/Desabilitar. Essa tradução precisa ser validada; Ativo/Inativo seria mais apropriado.` },
  { id: 'CX-498', module: 'SNMP & Poller', priority: 'baja', description: `Discovery Mapping — Onde se meciona Mapeamento de Descoberta se deve manter o termo técnico em inglês: Discovery Mapping` },
  { id: 'CX-499', module: 'SNMP & Poller', priority: 'baja', description: `Discovery — Onde se meciona Descoberta se deve manter o termo técnico em inglês: Discovery` },
  { id: 'CX-501', module: 'SNMP & Poller', priority: 'media', description: `Filtros do Discovery — Alterar a descriçao do campo Nome IP para Hostname` },
  { id: 'PM-003', module: 'Alarmas', priority: 'baja', description: `Catálogo > Limiares — Gerenciamento de Performance > Catálogo > Limiares > Case 3 - UGW - Ef. Handover LTE>WLAN. Identificamos que as opções do campo "Operador de Criticidade" estão sendo exibidas em inglês. Recomendamos ajustar para que todas as opções sejam apresentadas em português, garantindo maior consistência e melhor experiência para o usuário.` },
  { id: 'PM-007', module: 'Alarmas', priority: 'baja', description: `Catálogo > Limiares — Gerenciamento de Performance > Catálogo > Limiares > Filtro. Identificamos que, ao utilizar o filtro de KPI Associado a condição "contém" está sendo exibida em inglês como "contains".` },
  { id: 'PM-008', module: 'Alarmas', priority: 'baja', description: `Catálogo > Limiares — Gerenciamento de Performance > Catálogo > Limiares > Filtro > Status. Identificamos que opção Desabilidado do campo status está em inglês.` },
  { id: 'PM-009', module: 'Reporte', priority: 'baja', description: `Relatórios — Gerenciamento de Relatórios > Relatórios > Minsait QA > Relatório de Redes Fusion Baroneza - HLs > Elementos de rede > Adicionar elementos de rede > Instâncias de Equipamento > Filtros, identificamos que, após selecionar o campo no filtro, o nome do bloco DEVICE em que está o campo "DEVICENAME" está sendo exibido em inglês.` },
  { id: 'PM-010', module: 'Alarmas', priority: 'baja', description: `Catálogo > Limiares — Gerenciamento de Performance > Catálogo > Limiares > Case 3 - UGW - Ef. Handover LTE>WLAN. Identificamos que a opção "Critical" do campo "Criticidade do alarme" está sendo exibida em inglês. Recomendamos ajustar para que seja apresentada em português, garantindo maior consistência e melhor experiência para o usuário.` },
  { id: 'PM-011', module: 'Alarmas', priority: 'baja', description: `Catálogo > Limiares — Gerenciamento de Performance > Catálogo > Limiares > Filtro > Status. Identificamos que opção Habilidado do campo status está em inglês.` },
  { id: 'PM-012', module: 'KPI View & Navigator', priority: 'baja', description: `KPI View — Gerenciamento de Performance > KPI View > Adicionar filtro > nome do equipamento. Foi identificado que, ao selecionar o filtro nome do equipamento, o nome apresentado está com a inicial em minúsculo, diferenciando dos demais, e como sugestão ficaria Nome do equipamento.` },
  { id: 'PM-015', module: 'KPI View & Navigator', priority: 'baja', description: `KPI View — Gerenciamento de Performance > Portal de Performance > KPI View > Gráfico com KPIs selecionados. Foi identificado que no gráfico o eixo Valor está em inglês (Value), o que poderia ser substituído por uma mensagem adequada em português.` },
  { id: 'PM-016', module: 'KPI View & Navigator', priority: 'baja', description: `KPI View — Gerenciamento de Performance > KPI View > Adicionar filtro > Propriedades Description / Propriedades IP. Foi identificado que, ao selecionar o filtro Propriedades Description, o nome apresentado está em inglês, sendo sugerido em português Descrição, e Propriedade IP sendo mostrado como IP, sendo sugerido que seja mostrado como Propriedades IP para identificar que o IP é do filtro Propriedades.` },
  { id: 'PM-018', module: 'KPI View & Navigator', priority: 'baja', description: `KPI View — Gerenciamento de Performance > KPI View > DEVICE > Adicionar filtro > Propriedades Description. Foi identificado que, ao selecionar o filtro \'Propriedades Description\', o termo \'Description\' aparece em inglês, diferentemente dos demais filtros, que estão em português. Para manter a consistência, recomenda-se a tradução para o português.` },
  { id: 'PM-019', module: 'Alarmas', priority: 'baja', description: `Catálogo > Limiares — Gerenciamento de Performance > Catálogo > Limiares > Case 3 - UGW - Ef. Handover LTE>WLAN. Identificamos que a opção "Cleared" do campo "Criticidade do alarme" está sendo exibida em inglês. Recomendamos ajustar para que seja apresentada em português, garantindo maior consistência e melhor experiência para o usuário.` },
  { id: 'PM-020', module: 'Reporte', priority: 'baja', description: `Relatórios — Gerenciamento de Relatórios > Relatórios > Minsait QA > Relatório de Redes Fusion Baroneza - HLs > Elementos de rede > Adicionar elementos de rede > Instâncias de Equipamento > Filtros, identificamos que, após selecionar o campo no filtro, o nome do bloco DEVICE em que está o campo "Description" está sendo exibido em inglês.` },
  { id: 'PM-022', module: 'Alarmas', priority: 'baja', description: `Catálogo > Limiares — Gerenciamento de Performance > Catálogo > Limiares > Filtro > Status. Identificamos que a condição do campo "Status" está sendo exibida em inglês como "IS". Recomendamos ajustar para que a condição seja apresentada em português, proporcionando uma experiência mais adequada e consistente para o usuário.` },
  { id: 'PM-023', module: 'KPI View & Navigator', priority: 'baja', description: `KPI View — Gerenciamento de Performance > KPI View > Adicionar filtro > Localizações Area. Foi identificado que, ao selecionar o filtro Localizações Area, a palavra Area está faltando o acento, Área.` },
  { id: 'PM-024', module: 'Alarmas', priority: 'baja', description: `Catálogo > Limiares — "Gerenciamento de Performance > Catálogo > Limiares > Adicionar Limite. Identificamos que, ao preencher todos os campos necessários para criar um limite e selecionar a opção ""Expressão do KPI"" no campo ""KPI ou Expressão"", ao abrir o pop-up, o texto exibido contém um caractere "">"" ao final da frase:
      ""Para adicionar KPIs à lista, use o filtro de domínio e/ou a categoria do campo pesquisado e clique no botão adicionar. >""      Recomendamos remover esse caractere para melhorar a apresentação e a clareza da mensagem ao usuário."` },
  { id: 'PM-025', module: 'Alarmas', priority: 'baja', description: `Catálogo > Limiares — Gerenciamento de Performance > Catálogo > Limiares > Case 3 - UGW - Ef. Handover LTE>WLAN. Identificamos que a opção "Less than or equal" do campo "Operador de Criticidade" está sendo exibida em inglês. Recomendamos ajustar a opção para que seja apresentada em português, garantindo maior consistência e melhor experiência para o usuário.` },
  { id: 'PM-026', module: 'Reporte', priority: 'baja', description: `Relatórios — Gerenciamento de Relatórios > Relatórios > Árvore de Relatórios > Teste Delete. Informamos que ao tentar deletar uma categoria que possui subcategorias, identificamos que a mensagem exibida está em inglês. Recomendamos que a mensagem seja apresentada em português para melhorar a experiência do usuário.` },
  { id: 'PM-032', module: 'Reporte', priority: 'media', description: `Relatórios > Criar Relatório — Gerenciamento de Relatórios > Configuração de Relatórios > Relatórios > Criar Relatório > Detalhes. Preenchemos os campos no frame de detalhes com as seguintes informações: Nome do Relatório = "Relatório de Redes Fusion Baroneza - HLs v2", Categoria = "Minsait QA", Fuso Horário = "Meu fuso horário" e Descrição = "Relatório de Redes Fusion Baroneza - HLs v2". No frame Elementos de Rede, selecionamos SNMP > INTERFACE no campo Objeto Gerenciado. Em seguida, clicamos no botão Adicionar elementos de rede, acessamos o grupo de Equipamentos, clicamos em Minsait, selecionamos o grupo Rede Fusion Baroneza - HLs e clicamos em Salvar. Após isso, fomos redirecionados para a criação do relatório e clicamos no botão Próximo. No frame KPIs/Contadores, clicamos no botão + Adicionar KPIs, o que abriu um popup para adicionar um KPI. Durante a seleção do campo Taxa no filtro, identificamos que o operador "é" possui as opções de Sim e Não exibido em inglês.` },
  { id: 'PM-034', module: 'KPI View & Navigator', priority: 'baja', description: `KPI View — Gerenciamento de Performance > KPI View > MGW Huawei > Adicionar filtro > parentEquipament nome do equipamento. Foi identificado que, ao selecionar o filtro parentEquipament nome do equipamento, está escrito de forma diferente dos demais da mesma categoria, que estão todos em maiúsculo, parentEquipament VENDOR, parentEquipament DEVICENAME.` },
  { id: 'PM-036', module: 'Reporte', priority: 'baja', description: `Relatórios — Gerenciamento de Relatórios > Relatórios > Minsait QA > Relatório de Redes Fusion Baroneza - HLs > Elementos de rede > Adicionar elementos de rede > Instâncias de Equipamento > Filtros, identificamos que o campo "Area" está sendo exibido sem o acento agudo ("Área") no filtro.` },
  { id: 'PM-037', module: 'Reporte', priority: 'baja', description: `Relatórios — Gerenciamento de Relatórios > Relatórios > Minsait QA > Relatório de Redes Fusion Baroneza - HLs > Elementos de rede > Adicionar elementos de rede > Instâncias de Equipamento > Filtros, identificamos que, após selecionar o campo no filtro, o nome do bloco DEVICE em que está o campo "Tipo de rede" está sendo exibido em inglês.` },
  { id: 'PM-038', module: 'Alarmas', priority: 'baja', description: `Catálogo > Limiares — Gerenciamento de Performance > Catálogo > Limiares > Filtro. Identificamos que o título do filtro está sendo exibido em inglês como "Filters". Recomendamos ajustar para que o termo seja apresentado em português, garantindo maior consistência e melhor experiência para o usuário.` },
  { id: 'PM-039', module: 'Reporte', priority: 'baja', description: `Relatórios — Gerenciamento de Relatórios > Relatórios > Minsait QA > Relatório de Redes Fusion Baroneza - HLs > Elementos de rede > Adicionar elementos de rede > Instâncias de Equipamento > Filtros, identificamos que, após selecionar o campo no filtro, o nome do bloco DEVICE em que está o campo "nome" está sendo exibido em inglês.` },
  { id: 'PM-041', module: 'Alarmas', priority: 'baja', description: `Catálogo > Limiares — Gerenciamento de Performance > Catálogo > Limiares > Adicionar Limite. Identificamos que, ao preencher todos os campos necessários para criar um limite e selecionar a opção "Expressão do KPI" no campo "KPI ou Expressão", ao abrir o pop-up, ao selecionar "1 dia" no campo "Granularidade" e clicar no campo "Domínio", a mensagem exibida quando não há opções disponíveis aparece em inglês ("No options"). Recomendamos ajustar essa mensagem para o idioma português, garantindo uma experiência mais consistente para o usuário.` },
  { id: 'PM-042', module: 'Reporte', priority: 'media', description: `Relatórios > Criar Relatório — Gerenciamento de Relatórios > Configuração de Relatórios > Relatórios > Criar Relatório > Detalhes. Preenchemos os campos no frame de detalhes com as seguintes informações: Nome do Relatório = "Relatório de Redes Fusion Baroneza - HLs v2", Categoria = "Minsait QA", Fuso Horário = "Meu fuso horário" e Descrição = "Relatório de Redes Fusion Baroneza - HLs v2". No frame Elementos de Rede, selecionamos SNMP > INTERFACE no campo Objeto Gerenciado. Em seguida, clicamos no botão Adicionar elementos de rede, acessamos o grupo de Equipamentos, clicamos em Minsait, selecionamos o grupo Rede Fusion Baroneza - HLs e clicamos em Salvar. Após isso, fomos redirecionados para a criação do relatório e clicamos no botão Próximo. No frame KPIs/Contadores, clicamos no botão + Adicionar KPIs, o que abriu um popup para adicionar um KPI. Durante a seleção do campo Status no filtro, identificamos que o operador "é" possui as opções de Habilitado e desabilitado exibido em inglês.` },
  { id: 'PM-044', module: 'Alarmas', priority: 'baja', description: `Catálogo > Limiares — Gerenciamento de Performance > Catálogo > Limiares > Adicionar Limite > Agregação de Dados. Identificamos que a opção Area está sem acentuação correta no campo Locations.` },
  { id: 'PM-045', module: 'KPI View & Navigator', priority: 'baja', description: `KPI View — Gerenciamento de Performance > Catálogo > KPI > Adicionar KPI ou Fórmula > KPIs (carga massiva) > Abrir link de instrução. Foi identificado que o link de instrução está com toda documentação em inglês.` },
  { id: 'PM-046', module: 'KPI View & Navigator', priority: 'baja', description: `KPI View — Gerenciamento de Performance > Portal de Performance > KPI View > Filtro > Botão Pesquisar por grupo de equipamento > Procurou por > Instâncias de Equipamento. Foi identificado que em Procurou por: ao escolher Grupo ou Instâncias de Equipamento é disparado um alerta com a mensagem em inglês Warning o que poderia ser substituído por uma mensagem adequada em português.` },
  { id: 'PM-047', module: 'Reporte', priority: 'baja', description: `Relatórios — Gerenciamento de Relatórios > Relatórios > Minsait QA > Relatório de Redes Fusion Baroneza - HLs > Elementos de rede > Adicionar elementos de rede > Instâncias de Equipamento > Filtros > Equipamento > Tipo, identificamos que, ao utilizar o filtro "Tipo de Equipamento", é exibida uma mensagem relacionada ao campo "ID externo" com o valor "undefined", apresentada em inglês.` },
  { id: 'PM-048', module: 'Alarmas', priority: 'baja', description: `Catálogo > Limiares — Gerenciamento de Performance > Catálogo > Limiares > Case 3 - UGW - Ef. Handover LTE>WLAN. Identificamos que, no campo "Status", os dados estão sendo exibidos em inglês. Recomendamos ajustar para que as informações sejam apresentadas em português, garantindo maior consistência e melhor experiência para o usuário.` },
  { id: 'PM-049', module: 'Alarmas', priority: 'baja', description: `Catálogo > Limiares — Gerenciamento de Performance > Catálogo > Limiares > Case 3 - UGW - Ef. Handover LTE>WLAN. Identificamos que a opção "Major" do campo "Criticidade do alarme" está sendo exibida em inglês. Recomendamos ajustar para que seja apresentada em português, garantindo maior consistência e melhor experiência para o usuário.` },
  { id: 'PM-050', module: 'KPI View & Navigator', priority: 'baja', description: `KPI View — Gerenciamento de Performance > Portal de Performance > KPI View > Procurar Resultados > Pesquisar KPI. Foi identificado que na caixa Pesquisar KPI o texto da máscara da caixa de pesquisa está em inglês (Search Kpi), o que poderia ser substituído por uma mensagem adequada em português.` },
  { id: 'PM-053', module: 'Alarmas', priority: 'baja', description: `Catálogo > Limiares — Gerenciamento de Performance > Catálogo > Limiares > Adicionar Limite. Identificamos que o campo "Objeto Gerenciado" está sendo exibido em inglês. Recomendamos ajustar para que o nome do campo seja apresentado em português, garantindo maior consistência e melhor experiência para o usuário.` },
  { id: 'PM-055', module: 'Alarmas', priority: 'baja', description: `Catálogo > Limiares — Gerenciamento de Performance > Catálogo > Limiares > Filtro. Identificamos que, ao utilizar o filtro de nome a condição "contém" está sendo exibida em inglês como "contains".` },
  { id: 'PM-056', module: 'Reporte', priority: 'baja', description: `Relatórios — Gerenciamento de Relatórios > Relatórios > Minsait QA > Relatório de Redes Fusion Baroneza - HLs > Elementos de rede > Adicionar elementos de rede > Instâncias de Equipamento > Filtros, identificamos que, após selecionar o campo no filtro, o nome do bloco DEVICE em que está o campo "Tipo de elemento" está sendo exibido em inglês.` },
  { id: 'PM-057', module: 'KPI View & Navigator', priority: 'baja', description: `KPI View — Gerenciamento de Performance > KPI View > Adicionar filtro > KPI Domínio. Foi identificado que, ao selecionar o filtro KPI Domínio, o nome apresentado está diferente dos demais, sugerindo como padronização o nome: Domínio do KPI. E para os demais filtros do KPI também fica sugerido a padronização dos nomes, como Tipo de rede do KPI, Tecnologia do KPI.` },
  { id: 'PM-058', module: 'KPI View & Navigator', priority: 'baja', description: `KPI View — Gerenciamento de Performance > KPI View > Adicionar filtro > Equipamento IP. Foi identificado que, ao selecionar o IP da categoria Equipamento, o nome apresentado é IP, não sendo possível identificar que faz parte do Equipamento, e como sugestão poderia apresentar o nome como de outras categorias, por exemplo, Nível de granularidade, Nome do grupo. Poderia ser IP do equipamento.` },
  { id: 'PM-059', module: 'KPI View & Navigator', priority: 'baja', description: `KPI View — Gerenciamento de Performance > Portal de Performance > KPI View > Gráfico com KPIs selecionados. Foi identificado que no gráfico a caixa de listagem está em inglês (Refresh Time), o que poderia ser substituído por uma mensagem adequada em português.` },
  { id: 'PM-061', module: 'KPI View & Navigator', priority: 'baja', description: `KPI View — Gerenciamento de Performance > KPI View > UPF > Grupo UPF_POOL > User plane maximum assigned IP adress.... No Gráfico, foi identificado que o nome do eixo Y está em inglês (Number).` },
  { id: 'PM-063', module: 'Reporte', priority: 'baja', description: `Relatórios — Gerenciamento de Relatórios > Relatórios > Minsait QA > Relatório de Redes Fusion Baroneza - HLs > Elementos de rede > Adicionar elementos de rede > Instâncias de Equipamento > Filtros, identificamos que, após selecionar o campo no filtro, o nome do bloco DEVICE em que está o campo "nome do equipamento" está sendo exibido em inglês.` },
  { id: 'PM-064', module: 'Reporte', priority: 'media', description: `Relatórios > Criar Relatório — Gerenciamento de Relatórios > Configuração de Relatórios > Relatórios > Criar Relatório > Detalhes. Preenchemos os campos no frame de detalhes com as seguintes informações: Nome do Relatório = "Relatório de Redes Fusion Baroneza - HLs v2", Categoria = "Minsait QA", Fuso Horário = "Meu fuso horário" e Descrição = "Relatório de Redes Fusion Baroneza - HLs v2". No frame Elementos de Rede, selecionamos SNMP > INTERFACE no campo Objeto Gerenciado. Em seguida, clicamos no botão Adicionar elementos de rede, acessamos o grupo de Equipamentos, clicamos em Minsait, selecionamos o grupo Rede Fusion Baroneza - HLs e clicamos em Salvar. Após isso, fomos redirecionados para a criação do relatório e clicamos no botão Próximo. No frame KPIs/Contadores, clicamos no botão + Adicionar KPIs, o que abriu um popup para adicionar um KPI. Durante a seleção do campo Taxa no filtro, identificamos que após confirmar o filtro, a aplicação está transformando "SIM" ou "Não" em true e false.` },
  { id: 'PM-065', module: 'Reporte', priority: 'baja', description: `Relatórios > Árvore de relatórios — Gerenciamento de Relatórios > Gerenciamento de Relatórios > Relatórios > Árvore de relatórios > Teste Delete. Informamos que ao tentar deletar a categoria "Teste Delete", identificamos que a mensagem apresentada está em inglês.` },
  { id: 'PM-067', module: 'KPI View & Navigator', priority: 'baja', description: `KPI View — Gerenciamento de Performance > Catálogo > KPI > Filtro > Status. No filtro \'Status\', as opções estão sendo exibidas em inglês Disabled e Enabled. Sugere-se que sejam apresentadas em português para melhor adequação ao idioma do sistema.` },
  { id: 'PM-068', module: 'Alarmas', priority: 'baja', description: `Catálogo > Limiares — Gerenciamento de Performance > Catálogo > Limiares > Case 3 - UGW - Ef. Handover LTE>WLAN. Identificamos que as opções do campo "Criticidade do alarme" estão sendo exibidas em inglês. Recomendamos ajustar para que todas as opções sejam apresentadas em português, garantindo maior consistência e melhor experiência para o usuário.` },
  { id: 'PM-069', module: 'Alarmas', priority: 'baja', description: `Catálogo > Limiares — Gerenciamento de Performance > Catálogo > Limiares > Case 3 - UGW - Ef. Handover LTE>WLAN. Identificamos que a opção "Less Than" do campo "Operador de Criticidade" está sendo exibida em inglês. Recomendamos ajustar a opção para que seja apresentada em português, garantindo maior consistência e melhor experiência para o usuário.` },
  { id: 'PM-070', module: 'KPI View & Navigator', priority: 'baja', description: `KPI View — Gerenciamento de Performance > Portal de Performance > KPI View > Frase de filtro. Identificamos que o texto menciona corretamente os campos \'Período\' e \'Objeto Gerenciado\' como obrigatórios. No entanto, o campo \'Valor\', que também está marcado como obrigatório, não foi contemplado na frase do filtro.` },
  { id: 'PM-071', module: 'KPI View & Navigator', priority: 'baja', description: `Catálogo > KPI > Adicionar KPI ou Fórmula — Gerenciamento de Performance > Catálogo > KPI > Adicionar KPI ou Fórmula > KPI único > Fórmula > Campo contadores. Foi identificado que o campo Contadores está com texto em inglês.` },
  { id: 'PM-072', module: 'Alarmas', priority: 'baja', description: `Catálogo > Limiares — Gerenciamento de Performance > Catálogo > Limiares > Adicionar Limite. Identificamos que o botão "+ add Expression*" está sendo exibido em inglês. Recomendamos ajustar para que o texto do botão seja apresentado em português, garantindo maior consistência e melhor experiência para o usuário.` },
  { id: 'PM-076', module: 'Alarmas', priority: 'baja', description: `Catálogo > Limiares — Gerenciamento de Performance > Catálogo > Limiares > Case 3 - UGW - Ef. Handover LTE>WLAN. Identificamos que a opção "Minor" do campo "Criticidade do alarme" está sendo exibida em inglês. Recomendamos ajustar para que seja apresentada em português, garantindo maior consistência e melhor experiência para o usuário.` },
  { id: 'PM-077', module: 'KPI View & Navigator', priority: 'baja', description: `KPI View — Gerenciamento de Performance > Portal de Performance > KPI View > Período > Selecione o período > De. Identificamos que o campo \'De\' está exibindo o calendário com data e hora no formato inglês, o que pode causar inconsistências ou confusão para os usuários.` },
  { id: 'PM-078', module: 'KPI View & Navigator', priority: 'baja', description: `KPI View — Gerenciamento de Performance > Portal de Performance > KPI View > Gráfico com KPIs selecionados > Legenda do ponto. Foi identificado que ao posicionar no ponto do gráfico, está exibindo títulos da Agregação em inglês, como Used, Temporal agg, Spatial agg, o que poderia ser substituído por uma mensagem adequada em português.` },
  { id: 'PM-079', module: 'Reporte', priority: 'baja', description: `Relatórios — Gerenciamento de Relatórios > Relatórios > Minsait QA > Relatório de Redes Fusion Baroneza - HLs > Elementos de rede > Adicionar elementos de rede > Instâncias de Equipamento > Filtros, identificamos que o campo "Função" não está seguindo o mesmo padrão de nomenclatura do campo "Nome", que, por estar no bloco de equipamento, é apresentado como "Nome do equipamento".` },
  { id: 'PM-080', module: 'KPI View & Navigator', priority: 'baja', description: `KPI View — Gerenciamento de Performance > KPI View > UPF > Grupo UPF_POOL > User plane maximum assigned IP adress.... No Gráfico, foi identificado que na legenda está em inglês (Number).` },
  { id: 'PM-081', module: 'KPI View & Navigator', priority: 'baja', description: `KPI View — Gerenciamento de Performance > KPI View > Adicionar filtro. Foi identificado que, ao digitar um texto que não corresponde a nenhum item da lista do filtro selecionado, é exibida a mensagem em inglês "No matches". O ideal seria que essa mensagem fosse apresentada em português, como por exemplo: "Nenhuma correspondência encontrada".` },
  { id: 'PM-085', module: 'Alarmas', priority: 'baja', description: `Catálogo > Limiares — Gerenciamento de Performance > Catálogo > Limiares > Case 3 - UGW - Ef. Handover LTE>WLAN. Identificamos que a opção "Greater than or equal" do campo "Operador de Criticidade" está sendo exibida em inglês. Recomendamos ajustar a opção para que seja apresentada em português, garantindo maior consistência e melhor experiência para o usuário.` },
  { id: 'PM-087', module: 'KPI View & Navigator', priority: 'baja', description: `KPI View — Gerenciamento de Performance > KPI View > Adicionar filtro > Equipamento Função. Foi identificado que, ao selecionar o filtro Equipamento Função, o nome apresentado está diferente dos demais, sugerindo como padronização o nome: Função do equipamento. E para os demais filtros do Equipamento também fica sugerido a padronização dos nomes, como Credenciais do Equipamento, Modelo do equipamento, DN do equipamento, Fornecedor do equipamento.` },
  { id: 'PM-090', module: 'Reporte', priority: 'baja', description: `Relatórios — Gerenciamento de Relatórios > Relatórios > Minsait QA > Relatório de Redes Fusion Baroneza - HLs > Elementos de rede > Adicionar elementos de rede > Instâncias de Equipamento. Identificamos que, ao selecionar a opção "Instâncias de Equipamento", é exibida uma mensagem de alerta em que a palavra "aviso" está escrita em inglês.` },
  { id: 'PM-091', module: 'Alarmas', priority: 'baja', description: `Catálogo > Limiares — Gerenciamento de Performance > Catálogo > Limiares > Filtro. Identificamos que, ao utilizar o filtro de nome e inserir um valor para busca, a condição "contém" está sendo exibida em inglês como "contains". Recomendamos ajustar para que a condição seja apresentada em português, garantindo maior consistência e melhor experiência para o usuário.` },
  { id: 'PM-092', module: 'Reporte', priority: 'media', description: `Relatórios > Criar Relatório — Gerenciamento de Relatórios > Configuração de Relatórios > Relatórios > Criar Relatório > Detalhes. Preenchemos os campos no frame de detalhes com as seguintes informações: Nome do Relatório = "Relatório de Redes Fusion Baroneza - HLs v2", Categoria = "Minsait QA", Fuso Horário = "Meu fuso horário" e Descrição = "Relatório de Redes Fusion Baroneza - HLs v2". No frame Elementos de Rede, selecionamos SNMP > INTERFACE no campo Objeto Gerenciado. Em seguida, clicamos no botão Adicionar elementos de rede, acessamos o grupo de Equipamentos, clicamos em Minsait, selecionamos o grupo Rede Fusion Baroneza - HLs e clicamos em Salvar. Após isso, fomos redirecionados para a criação do relatório e clicamos no botão Próximo. No frame KPIs/Contadores, clicamos no botão + Adicionar KPIs, o que abriu um popup para adicionar um KPI. Durante a seleção do campo Tem Fórmula no filtro, identificamos que após confirmar o filtro, a aplicação está transformando "SIM" ou "Não" em true e false.` },
  { id: 'PM-094', module: 'Reporte', priority: 'baja', description: `Relatórios — Gerenciamento de Relatórios > Relatórios > Minsait QA > Relatório de Redes Fusion Baroneza - HLs > Elementos de rede > Adicionar elementos de rede > Instâncias de Equipamento > Filtros, identificamos que, após selecionar o campo no filtro, o nome do bloco DEVICE em que está o campo "IP" está sendo exibido em inglês.` },
  { id: 'PM-096', module: 'KPI View & Navigator', priority: 'baja', description: `KPI View — Gerenciamento de Performance > Portal de Performance > KPI View > Descrição da tela. Identificamos que o texto menciona corretamente os campos \'Período\' e \'Objeto Gerenciado\' como obrigatórios. No entanto, o campo \'Valor\', que também está marcado como obrigatório, não foi contemplado na descrição.` },
  { id: 'PM-097', module: 'Alarmas', priority: 'baja', description: `Portal de Performance > Alarmes — Gerenciamento de Performance > Portal de Performance > Alarmes > Tabela > Severity. Identificamos que, na tabela, as opções do campo "Severity" estão sendo exibidas em inglês. Recomendamos ajustar para que todas as opções sejam apresentadas em português, garantindo maior consistência e melhor experiência para o usuário.` },
  { id: 'PM-101', module: 'Alarmas', priority: 'baja', description: `Catálogo > Limiares > Filtro — Gerenciamento de Performance > Catálogo > Limiares > Filtro. Identificamos que, ao utilizar o filtro de Algoritmo a condição "é" está sendo exibida em inglês como "is".` },
  { id: 'PM-102', module: 'Reporte', priority: 'baja', description: `Relatórios — Gerenciamento de Relatórios > Relatórios > Minsait QA > Relatório de Redes Fusion Baroneza - HLs > Elementos de rede > Adicionar elementos de rede > Instâncias de Equipamento > Filtros, identificamos que, após selecionar o campo no filtro, o nome do bloco DEVICE em que está o campo "Regional" está sendo exibido em inglês.` },
  { id: 'PM-103', module: 'KPI View & Navigator', priority: 'baja', description: `KPI View — Gerenciamento de Performance > Portal de Performance > KPI View > Período > Selecione o período > Até*. Identificamos que o campo \'Até\' está exibindo o calendário com data e hora no formato inglês, o que pode causar inconsistências ou confusão para os usuários.` },
  { id: 'PM-104', module: 'KPI View & Navigator', priority: 'baja', description: `KPI View — Gerenciamento de Performance > KPI View > MGW Huawei > P_EFICI_TRANSM_PACOTES. Foi identificado que, ao gerar o gráfico a legenda está em inglês, como NONE, AVG, e como sugestão que ficasse em português para maior clareza.` },
  { id: 'PM-106', module: 'Reporte', priority: 'media', description: `Agendamento de Relatórios — Gerenciamento de Relatórios > Agendamento de Relatórios > CANG_POOLIP_PM2_DIARIO_HUDSON. Informamos que a mensagem exibida no campo "Data de execução" está em inglês (Date should not be before minimal date).` },
  { id: 'PM-107', module: 'Reporte', priority: 'baja', description: `Relatórios — Gerenciamento de Relatórios > Relatórios > Minsait QA > Relatório de Redes Fusion Baroneza - HLs > Elementos de rede > Adicionar elementos de rede > Instâncias de Equipamento > Filtros, identificamos que, após selecionar o campo no filtro, o nome do bloco DEVICE em que está o campo "UF" está sendo exibido em inglês.` },
];

async function run() {
  let updated = 0; let inserted = 0;
  for (const item of ITEMS) {
    const existing = await db.select().from(cxItemsTable).where(sql`id = ${item.id}`);
    if (existing.length > 0) {
      await db.update(cxItemsTable)
        .set({ description: item.description, module: item.module, priority: item.priority })
        .where(sql`id = ${item.id}`);
      updated++;
    } else {
      await db.insert(cxItemsTable).values({
        id: item.id, module: item.module, type: 'traduccion',
        priority: item.priority, description: item.description,
        status: 'sin-evaluar', position: 0,
      });
      inserted++;
    }
  }
  console.log(`Done: ${updated} updated, ${inserted} inserted`);
  await client.end();
}

run().catch(console.error);
